### ISSUE TITLE
Facebook login not work

### ISSUE THREAD

**Issue by victorpierre789** [onearmbandit/Fb-Twiiter-Google-likedin-login#1]
STEP 1 : (is good)
![simulator screen shot 13 nov 2016 a 15 32 11](https://cloud.githubusercontent.com/assets/15923585/20246503/4f33126c-a9b8-11e6-8176-e635fa026b9a.png)

STEP 2 : (not work / white page / not redirect on ViewControllerForFacebookDash)

![simulator screen shot 13 nov 2016 a 15 32 16](https://cloud.githubusercontent.com/assets/15923585/20246504/4f5cf622-a9b8-11e6-9733-8da060b4201b.png)

**Comment by sudhir-oab** [comment]
Hi Victor,

The facebook login issue has been resolved.
